CREATE TABLE noteapp.users ( 
	id INT(50) NOT NULL AUTO_INCREMENT , 
	email VARCHAR(150) NULL DEFAULT NULL , 
	name VARCHAR(150) NULL DEFAULT NULL , 
	username VARCHAR(150) NULL DEFAULT NULL , 
	password VARCHAR(150) NULL DEFAULT NULL , 
	INDEX (id)) ENGINE = InnoDB;

CREATE TABLE noteapp.notes ( 
	id INT(50) NOT NULL AUTO_INCREMENT , 
	title VARCHAR(100) NULL DEFAULT NULL , 
	body VARCHAR(450) NULL DEFAULT NULL , 
	username VARCHAR(150) NULL DEFAULT NULL , 
	INDEX (id)) ENGINE = InnoDB;

FLUSH PRIVILEGES;